Dev
WildCodeSchool-2024-02/JS-lyon-0224-P2-cover_4_you pull request #51
Opened 2024-04-26 14:16 UTC by LoicLeg69

US17 - [Accueil] Dynamiser la vitrine
US27 - [Livre] Faire apparaitre le nombre de page des livres
US43 - [Home] - Ajouter un effet de chargement de page
US09 - [Accueil] Vitrine de livres personnalisés
US48 - [Livre] - Rajouter un Toast au clic de commande couverture personnalisée
US11 - [Livre] Personnaliser la couverture avec l'image importée de l'utilisateur
US08 - [Livre] Bouton commander
US47 - [Livre] - Css Bouton choisir un fichier
US38 - [Résultat] - Réinitialiser le contenu de la barre de recherche après une recherche
US44 - [NavBar] - Rendre le logo cliquable pour revenir à Home
US40 - [Barre de recherche] - Améliorer le CSS de la barre de recherche
US41 - [Barre de recherche] Configurer la touche 'Enter' pour lancer la recherche
US03 - [Livre] Synopsis du livre

2024-04-27 12:42 UTC, wildmatthieu requested changes

2024-04-27 12:42 UTC, wildmatthieu commented on client/src/App.module.css
> +  /* box-sizing: border-box; */
code commenté = code mort : à retirer :)

2024-04-27 12:42 UTC, wildmatthieu commented on client/src/component_home/BookBanner/BookBanner.module.css
>  .bookBanner > * {
attention au sélecteur * qui peut provoquer des comportements non attendus en plus d'être plus gourmand en terme de performance sur l'affichage d'une page web. 
Vérifiez bien que vous n'avez pas d'autres solutions en dehors de l'utilisation du sélécteur *

2024-04-27 12:42 UTC, wildmatthieu commented on client/src/component_home/BookStyle/BookStyle.jsx
> +              book.cover_i
explicitez vos conditions : 
book.cover_i === true ?
book.cover_i === false ?
book.cover_i.length > 0 ?
...

2024-04-27 12:42 UTC, wildmatthieu commented on client/src/component_home/ButtonFav/ButtonFav.jsx
> +        if (favorite) {
explicitez votre condition : favorite
favorite === ?

2024-04-27 12:42 UTC, wildmatthieu commented on client/src/pages/Home.jsx
> +      {isLoading && (
explicitez votre condition : 
isLoading === ?

2024-04-27 12:42 UTC, wildmatthieu commented on client/src/pages/ResultPage.jsx
> +      {isLoading && (
explicitez votre condition : 
isLoading === ?

2024-04-27 15:46 UTC, HazeFury commented on client/src/component_home/Nav/Nav.jsx
> +              ? styles.burger_nav_open
Je vous conseille de passer plutôt par une img dans votre bouton (donc importez vos 2 icônes dans le JSX et faite votre ternaire avec ^^ ).

Cela évitera de devoir faire du CSS un peu bizarre pour les images du menu burger 😉

2024-04-27 15:48 UTC, HazeFury commented on client/src/component_home/Nav/Nav.jsx
> +              <a href={styles.navbar_route}>Our Librairie</a>
je comprend maintenant pourquoi les liens du menu ne marchent pas.

Vous avez confondu href et className ==> à rectifier

2024-04-27 15:50 UTC, HazeFury commented on client/src/component_home/Nav/Nav.jsx
> +          {/* LogoHome */}
pas de code commenté !

2024-04-27 15:53 UTC, HazeFury commented on client/src/component_home/Nav/Nav.module.css
> +.navbar_route {
pas la peine de mettre cette règle CSS vu que la balise a le fait déjà nativement

2024-04-27 16:27 UTC, HazeFury commented on client/src/pages/Home.jsx
> +      "dragon+ball+z",
les 2 derniers ne renvoient pas d'images chez moi ==> pour la démo, prenez en d'autres histoire d'avoir d'être sûr d'avoir des images ^^

2024-04-27 16:35 UTC, HazeFury requested changes
Du bon boulot dans l'ensemble, bien joué !! 👍 🥳 

En plus des commentaires que j'ai mis sur les différents fichiers, voici des retours global que j'ai observé en testant votre application sur mon ordi (certains sont des reddit que ce que j'ai mis dans les fichier ^^) : 

- erreur dans "Find your farorite book covers" ==> "favorite"

- d'après mes recherches, je pencherais plus pour "customize" au lieu de "customise" ^^

- sur la page d'accueil : en dessous de la barre de recherche, certaines images ne chargent pas

- sur la page d'accueil : en dessous de "Find your farorite book covers", parfois il n'y a aucune image et il y a l'alt "livreNaN"

- sur la page d'accueil : les livres de "Find your farorite book covers" changent trop vite => pas le temps de bien les voir + parfois le même livre est affiché 2 fois (EDIT : bon c'est peut-être dû au React.strictMode donc on ne peux pas y faire grand chose en fait)  

- les liens du menu burger ne fonctionne pas, ils renvoient sur une 404, est-ce normal ??

- je peux cliquer sur le bouton de recherche même si la barre de recherche est vide, ce qui provoque une erreur

- parfois lorsque je recharge la page, la navbar n'apparait plus

2024-04-29 07:41 UTC, fadili6 commented on client/src/component_home/BookStyle/BookStyle.jsx
> +              book.cover_i
Code amélioré!

2024-04-29 09:37 UTC, wilderLPM commented
Merci pour vos commentaires. Il y a 2 choses que nous n'avons pas pu régler.
D'une part, la vitrine de la page **Accueil** n'affiche pas toujours d'images.
Deuxièmement, les images de la **navBar** disparaissent après certains rafraîchissement de page mais nous n'avons pas compris pourquoi.
Pour ce qui est du reste, nous nous en sommes occupés.

2024-04-29 10:29 UTC, StoicFrenchDev requested changes

2024-04-29 10:29 UTC, benrcd commented on client/src/pages/BookPage.jsx
> +  //  const allText = book.first_sentence
This code is very much dead

2024-04-29 13:52 UTC, wilderLPM commented on client/src/component_home/BookBanner/BookBanner.module.css
>  .bookBanner > * {
Nous avons testé et pris la décision de laisser ainsi car cela semblait comme la meilleure solution en terme de facilité + efficacité.

2024-04-29 13:54 UTC, HazeFury commented on client/src/component_home/BookBanner/BookBanner.module.css
> +  grid-template: 5vh 2.5vh 2.5vh 11vh 8vh/20vw 0.5fr 1fr;
Quelle est cette magie noire ?? 🤔

2024-04-29 14:00 UTC, wildmatthieu requested changes

2024-04-29 14:00 UTC, wildmatthieu commented on client/src/pages/Home.jsx
> +      {isLoading && (
?

2024-04-29 14:00 UTC, wildmatthieu commented on client/src/pages/BookPage.jsx
> +  //  const allText = book.first_sentence
code mort => à retirer du coup :)

2024-04-29 14:00 UTC, wildmatthieu commented on client/src/component_home/BookStyle/BookStyle.jsx
> +              book.cover_i
je ne vois pas la correction, actuellement dans le code nous avons : 
`book.cover_i ?`

la condition n'est pas explicite, il faut quelque chose comme : 

```
book.cover_i === true ?
book.cover_i === false ?
book.cover_i.length > 0 ?
```

2024-04-29 14:00 UTC, wildmatthieu commented on client/src/component_home/Nav/Nav.jsx
> +      {(isMenuOpen === true || isDesktop) && (
isDesktop a expliciter : 
isDesktop === ?

2024-04-29 14:00 UTC, wildmatthieu commented on client/src/pages/BookPage.jsx
> +            {extractDisplay ? "Read more" : "See less"}
condition à expliciter : extractDisplay

2024-04-29 14:16 UTC, HazeFury approved these changes
Le jour de gloire eeeeesssst arrivéééééé 💯 🥳 

Bravo à vous 👍

2024-04-29 14:17 UTC, merged